name: NodeJS with Webpack

on:
  push:
    # branches: [ "master" ]
    tags: [ "v*" ] # 仅匹配以v开头的标签（如v1.0.0、v2.1.3）
  # pull_request:
    # branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予创建Release的写权限
      packages: read  # 可选，防止其他权限冲突
    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm -g install pnpm
        pnpm install
        pnpm run build
    - name: Create 7z archive and set env var
      run: |
        GIT_VERSION=$(git rev-parse --short HEAD)
        echo "GIT_VERSION=${GIT_VERSION}" >> $GITHUB_ENV # 将变量写入 GITHUB_ENV 以便后续步骤使用
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          RELEASE_VERSION=${{ github.ref_name }} # 比如 v1.0.3
        else
          RELEASE_VERSION="dev" # 非标签触发时的默认值
        fi
        ARCHIVE_NAME="autox-sgcc-mqtt_${RELEASE_VERSION}-${GIT_VERSION}.zip"
        echo "ARCHIVE_NAME=${ARCHIVE_NAME}" >> $GITHUB_ENV # 将变量写入 GITHUB_ENV 以便后续步骤使用
        cd out
        7z a "${ARCHIVE_NAME}" "autox-sgcc-mqtt"
        echo "Archive created: ${ARCHIVE_NAME}"
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      # env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          files: |
              out/${{ env.ARCHIVE_NAME }}
          name: "AutoX-SGCC-MQTT Release ${{ github.ref_name }} (${{ env.GIT_VERSION }})"
          body: |
          Release built from commit: ${{ env.GIT_VERSION }}
          Build time: ${{ github.event.head_commit.timestamp }}
          Node.js version: ${{ matrix.node-version }}